---
title: "Session 1"
author: "Heather Childers"
format: html
editor: visual
---

## Session 1: 

### Create some Vectors

```{r}
# Create a vector
rain <- c(3,5,10.1, 6)

# Check the class in the CONSOLE
#class(rain)

#Scalar vector multiplication
3 * rain

# Store the scaled value by using the assignent operator, note storing the scaled value doesnt print the values
rain_scaled <- (5*rain)
```

### Create some Matrices

```{r}
#Create a sequence of values
my_values <- seq(from = 1, to = 10)

#Turn that sequence into a matrix
# matrix(data=___, nrow = ___, ncol = ____, byrow = _____)
my_matrix <- matrix(data=my_values, nrow = 2, ncol = 5, byrow = TRUE)
my_matrix

my_matrix_col <- matrix(data=my_values, nrow=2, ncol=5, byrow= FALSE)
my_matrix_col

```

```{r}
my_matrix2 <- matrix(data=my_values, nrow = 3, ncol = 4, byrow = TRUE)
```

```{r}

4 * my_matrix

my_values_2 <- seq(from = 21, to = 30)
my_matrix_2 <- matrix(my_values_2, nrow = 2, byrow = TRUE)

# Check it out:
my_matrix_2

```

### Matrix Math

```{r}
my_matrix + my_matrix_2

my_matrix_2 - my_matrix
```

### Matrix Multiplication

```{r}
cats <- matrix(data = c(0,4,3,1), nrow = 2, byrow = TRUE)
dogs <- matrix(data = c(6,-3,0,2), nrow = 2, byrow = TRUE)

cats
dogs
```

```{r}
cats %*% dogs
cats * dogs
```

### Leslie Matrix Problem

```{r}
insect_leslie <- matrix(data=c(0,0,600,0.2,0,0,0,0.08,0), 
                        nrow=3, 
                        ncol=3, 
                        byrow= TRUE)

insect_y0 <- matrix(data=c(1200,700,500),
                   nrow = 3,
                   ncol = 1,
                   byrow = TRUE)


```

#### EX1: Find the populatioin structure for each life stage at year 1

```{r}
insect_y1 <- insect_leslie%*%insect_y0
```

Find the population structure at t=2 years

```{r}
insect_y2 = insect_leslie%*%insect_y1
insect_y2
```
